declare module '*.jpg';
declare module '*.png';
declare module '*.gif';
declare module '*.env';
declare module '*.dds';
declare module '*.hdr';
declare module '*.glb';
declare module '*.gltf';
declare module '*.fx';